services:
  registry:
    ports:
      - '5000:5000'
    container_name: registry
    image: 'registry:3.0.0'
    environment:
      OTEL_TRACES_EXPORTER: "none"
      OTEL_METRICS_EXPORTER: "none"
    volumes:
      - /docker/registry:/var/lib/registry
      - ./config.yml:/etc/distribution/config.yml
